import { useState,type FormEvent } from 'react';
import { useNavigate,useSearchParams } from 'react-router-dom';
import { Eye, EyeOff, LockKeyhole, ShieldCheck, UserRound, ArrowRight } from 'lucide-react';
import { api,jsonInit } from '../services/api';
import { LoadingOverlay, useAppUI } from '../components/AppUI';

export default function LoginPage(){
  const [msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[showPassword,setShowPassword]=useState(false);
  const [sp]=useSearchParams(),nav=useNavigate(),ui=useAppUI();
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setMsg('');try{const fd=new FormData(e.currentTarget);await api('/api/auth/login',jsonInit('POST',Object.fromEntries(fd)));ui.toast('Signed in successfully.');nav(sp.get('next')||'/admin')}catch(e:any){setMsg(e.message);ui.toast(e.message||'Unable to sign in.','error')}finally{setLoading(false)}};
  return <><div className="login-page"><div className="login-shell"><section className="login-brand-panel"><div className="login-brand-mark"><ShieldCheck size={27}/></div><div><p className="login-brand-name">Integration Hub</p><p className="login-brand-tag">Enterprise Administration</p></div><div className="login-brand-copy"><span className="login-kicker">INTEGRATION HUB</span><h2>Secure administration for your connected asset environment.</h2><p>Manage environments, views, access roles, users and integration activity from one controlled workspace.</p></div><div className="login-security"><LockKeyhole size={17}/><span>Protected administrative access</span></div></section><section className="login-card"><div className="login-card-head"><p className="eyebrow">ADMINISTRATION PORTAL</p><h1>Welcome back</h1><p className="subtitle">Sign in with your administrator account to continue.</p></div><form onSubmit={submit}><div className="form-field"><label htmlFor="login">Username or email</label><div className="input-with-icon"><UserRound size={18}/><input id="login" name="login" autoComplete="username" placeholder="Enter username or email" required autoFocus/></div></div><div className="form-field"><label htmlFor="password">Password</label><div className="input-with-icon password-field"><LockKeyhole size={18}/><input id="password" name="password" type={showPassword?'text':'password'} autoComplete="current-password" placeholder="Enter your password" required/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} title={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{msg&&<p className="form-message error-message" role="alert">{msg}</p>}<button className="primary-button login-submit" disabled={loading}>Sign in <ArrowRight size={17}/></button></form><p className="login-footnote">Authorized personnel only. Access may be monitored for security and audit purposes.</p></section></div></div><LoadingOverlay show={loading} text="Signing in…"/></>;
}
